
apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels: 
    author: ctuana
spec:
  terminationGracePeriodSeconds: 0
  containers:
   - name: nginx
     image: nginx
     ports:
      - containerPort: 80
   - name: alpine
     image: alpine
     command: ['watch','wget','-qO-','localhost']