apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    tier: frontend
    app: nginx
spec:
  selector:
    matchLabels:
      env: production
  replicas: 3
  template: 
    metadata:
      name: httpd
      labels:
        env: production
    spec:
      containers:
        - name: httpd
          image: httpd:2.4-alpine